version: '3'
services:
    api:
        build: .
        ports:
            - "5000:80"
        environment:
                - ASPNETCORE_ENVIRONMENT=development
    view:
        build: View/Vue/studentbudgetapp/
        ports:
            - "8080:8080"
