version: '3'
services:
    api:
        build: .
        ports:
            - "5000:80"
            - "5001:443"
    view:
        build: View/Vue/studentbudgetapp/
        ports:
            - "8080:8080"
